### ISSUE TITLE
Cushion/Pillow

### ISSUE THREAD

**Issue by ArtemisiaTR** [Conquest-Reforged/Conquest-Reforged-Resourcepack#17]
-Red, blue and cyan cushion.
-There are cushion with crown and sword variants. Can be a toggle block.
-Berber pillow, Celtic pillow and possibly all the new carpet's pillow variations.

[cushions_and_pillows.zip](https://github.com/Conquest-Reforged/Conquest-Reforged-Resourcepack/files/6274678/cushions_and_pillows.zip)

**Comment by HIPPOKLEIDES** [comment]
[cushion.zip](https://github.com/Conquest-Reforged/Conquest-Reforged-Resourcepack/files/6305666/cushion.zip)
monster's edits
