### ISSUE TITLE
Item Model Edits

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Conquest-Reforged-Resourcepack#31]
- [x] **Rustic Fence** (flip horizontally)
- [x] **Wooden Roof Supports** (flip horizontally)
- [x] **Bamboo Fence/Dried Bamboo Fence** (flip horizontally)
- [x] **Simple Picket Fence** (shutter model orientation)
- [x] **Wicker Fence** (shutter model orientation)
- [x] **Old Wicker Fence** (shutter model orientation)
- [x] **Ladder (vanilla)** (modded ladder orientation)
- [x] **Hawthorn Bush**
- [x] **Cactus**
- [x] **Wooden Tankard** (goblet orientation)
- [x] **Metal Tankard** (goblet orientation)
- [x] **Fancy Marble Balustrade** (shutter model orientation)
- [x] **White Painted Wooden Railing Fence** (flip horizontally)
- [x] **Jam Jars**
- [x] **Iron Hatchet**
- [x] **Metal Stairs** (flip horizontally/wooden stair model orientation)

Would be nice:
- [ ] Rails (trapdoor model orientation)
- [ ] Fishing Net (shutter model orientation)
- [ ] Hanging Net (shutter model orientation)
- [x] Caribbean Royal Palm Leaves (rescale)
- [x] Old Caribbean Royal Palm Leaves (rescale)
- [x] Dried Tobacco Rack

**Comment by HIPPOKLEIDES** [comment]
don't really care for the suggested changes to rails and nets, but all others are done

**Comment by CreativeRealms** [comment]
Reopened because rustic fence and wooden roof supports don't seem to have changed.
