### ISSUE TITLE
carpets

### ISSUE THREAD

**Issue by Monsterfisch** [Conquest-Reforged/Conquest-Reforged-Resourcepack#36]
[carpets.zip](https://github.com/Conquest-Reforged/Conquest-Reforged-Resourcepack/files/6412013/carpets.zip)

**Comment by HIPPOKLEIDES** [comment]
[carpets_.zip](https://github.com/Conquest-Reforged/Conquest-Reforged-Resourcepack/files/6447944/carpets_.zip)

This zip only has the necessary 2 carpets. The rest were already added. Need better names than "blue" and "brwon crosshit".
