### ISSUE TITLE
Wart brick thing not appearing in GUI (should be in advanced carpentry)

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Conquest-Reforged-Resourcepack#4]
**Screenshots/Video**    
![wart where](https://user-images.githubusercontent.com/33978024/75081838-6bd6bd00-5519-11ea-998d-0fdcffc88b9b.png)

**Comment by Monsterfisch** [comment]
[ward_block.zip](https://github.com/Conquest-Reforged/Conquest-Reforged-Resourcepack/files/6490848/ward_block.zip)
