### ISSUE TITLE
more QA stuff for the mod

### ISSUE THREAD

**Issue by Monsterfisch** [Conquest-Reforged/Conquest-Reforged-Resourcepack#46]
[QA_17.05.2021.zip](https://github.com/Conquest-Reforged/Conquest-Reforged-Resourcepack/files/6550580/QA_17.05.2021.zip)

**Comment by HIPPOKLEIDES** [comment]
There's no model accompanying the ship lantern texture

**Comment by Monsterfisch** [comment]
[ship_lantern.zip](https://github.com/Conquest-Reforged/Conquest-Reforged-Resourcepack/files/6554830/ship_lantern.zip)
here you go
