### ISSUE TITLE
grass stair item model doesnt have proper display settings

### ISSUE THREAD

**Issue by Monsterfisch** [Conquest-Reforged/Conquest-Reforged-Resourcepack#49]
https://i.imgur.com/kFzVsP8.png

**Comment by Monsterfisch** [comment]
also duckweed can replace vertical slabs and vertical cornerblock
and lilypads have a color tint they shouldnt have

**Comment by Monsterfisch** [comment]
rosebush and sunflower have biometinting even through they shouldnt https://i.imgur.com/Ez1XRyz.png

**Comment by HIPPOKLEIDES** [comment]
latest version should address these if you want to check

**Comment by Monsterfisch** [comment]
confirmed
